---
title: "Sales Detail Summary"
author: "Vivek"
date: 20/Jun/2019
output: word_document
---

# Exploring Sales Detail Summary Data Set from Vaya Salon
### Importing Required Libraries
```{r}
library(readxl)
library(tidyverse)
library(knitr)
library(RColorBrewer)
```



### Importing Data Set
```{r message=FALSE, warning=FALSE, paged.print=FALSE}
z1<-read_excel("F:/DATA ANALYSIS/PROJECT/VAYA SALON/vaya.xlsx", 
    sheet = "Sales Detail Summary", col_types = c("text", 
        "numeric", "numeric", "text", "text", 
        "text", "text", "numeric", "numeric", 
        "numeric", "numeric", "numeric", 
        "numeric"))
class(z1)

kable(colSums(is.na(z1)))

z2<-subset(z1,select = -c(Date,Salon,Staff_2,Vendor_Code))

kable(summary(z2))
kable(head(z2))
str(z2)

```



### Total Number of tickets sold by each employee
```{r fig.width=10, message=FALSE, warning=FALSE, paged.print=FALSE}
m1<-z2%>%
  select(Staff_1,Ticket)%>%
  group_by(Staff_1)%>%
  summarise(count=sum(Ticket))
kable(m1)

ggplot(m1,aes(Staff_1,count,color=Staff_1))+
  theme_minimal()+
  geom_point(size=5)+
  geom_segment(aes(x=Staff_1,
                   y=0,
                   xend=Staff_1,
                   yend=count))+
  geom_text(aes(label=count),hjust=-0.3)+
  labs(x="Staff",y="Number of tickets",title="Number of tickets sold by each staff member")
```




### Net Amount generated by each staff member
```{r fig.width=10, message=FALSE, warning=FALSE, paged.print=FALSE}
m2<-z2%>%
  select(Staff_1,Net)%>%
  group_by(Staff_1)%>%
  summarise(count=sum(Net))%>%
  arrange(count)
kable(m2)

ggplot(m2,aes(Staff_1,count,color=Staff_1))+
  theme_minimal()+
  geom_point(size=5)+
  geom_segment(aes(x=Staff_1,
                   y=0,
                   xend=Staff_1,
                   yend=count))+
  geom_text(aes(label=count),hjust=-0.3)+
  labs(x="Staff",y="Total Sum",title="Total amount per employee")
```




### Number of Tickets by each employee
```{r fig.width=10, message=FALSE, warning=FALSE, paged.print=FALSE}
m3<-z2%>%
  select(Staff_1,Qty)%>%
  group_by(Staff_1)%>%
  summarise(count=sum(Qty))%>%
  arrange(count)
kable(m3)

ggplot(m3,aes(Staff_1,count,color=Staff_1))+
  theme_minimal()+
  geom_point(size=5)+
  geom_segment(aes(x=Staff_1,
                   y=0,
                   xend=Staff_1,
                   yend=count))+
  geom_text(aes(label=count),hjust=-0.5)+
  labs(x="Staff",y="Quantities of tickets",title="Quantities of tickets per employee")
```