---
title:"Ticket List"
author:"Vivek"
date:20/Jun/2019
output:html_document
---

# Exploring Ticket List Data set 

### Importing required libraries
```{r message=FALSE, warning=FALSE, paged.print=FALSE}
library(readxl)
library(tidyverse)
library(knitr)
```




### Importing Data set and Descriptive Statistics
```{r message=FALSE, warning=FALSE, paged.print=FALSE}
z1<-read_excel("F:/DATA ANALYSIS/PROJECT/VAYA SALON/vaya.xlsx", 
               sheet = "Ticket_List", col_types = c("text", 
                                                    "numeric", "text", "numeric", "text", 
                                                    "text", "text", "numeric", "text", 
                                                    "numeric", "numeric"))
dim(z1)
kable(colSums(is.na(z1)))
z1<-subset(z1,select=-c(Salon,Date,Time,Ticket,Payment))
z1<-na.omit(z1)
kable(colSums(is.na(z1)))
str(z1)
```



### Number of tickets attended by staff
```{r fig.width=10, message=FALSE, warning=FALSE, paged.print=FALSE}
m1<-z1%>%
  select(Ticket_Staff)%>%
  group_by(Ticket_Staff)%>%
  summarise(count=n())%>%
  arrange(count)
kable(m1)

ggplot(m1,aes(Ticket_Staff,count,color=Ticket_Staff))+
  theme_minimal()+
  geom_point(size=5)+
  geom_segment(aes(x=Ticket_Staff,
                   y=0,
                   xend=Ticket_Staff,
                   yend=count))+
  geom_text(aes(label=count),hjust=-0.6)+
  labs(x="Staff",y="Tickets",title="Total number of tickets per Staff")
```



### One or more revisits by Customers
```{r}
m2<-z1%>%
  select(Customer)%>%
  group_by(Customer)%>%
  summarise(count=n())%>%
  arrange(count)
kable(tail(m2))
```



### Amount generated by each staff member
```{r fig.width=10, message=FALSE, warning=FALSE, paged.print=FALSE}
m3<-z1%>%
  select(Ticket_Staff,Amount)%>%
  group_by(Ticket_Staff)%>%
  summarise(count=sum(Amount))%>%
  arrange(count)
kable(m3)

ggplot(m3,aes(Ticket_Staff,count,color=Ticket_Staff))+
  theme_minimal()+
  geom_point(size=5)+
  geom_segment(aes(x=Ticket_Staff,
                   y=0,
                   xend=Ticket_Staff,
                   yend=count))+
  geom_text(aes(label=count),hjust=-0.4)+
  labs(x="Staff",y="Amount",title="Total Amount per Staff")
```



### Total amount per Status
```{r}
m4<-z1%>%
  select(Status,Amount)%>%
  group_by(Status)%>%
  summarise(count=sum(Amount))%>%
  arrange(count)
kable(m4)
```




### Total Amount paid by each customer
```{r}
m5<-z1%>%
  select(Customer,Amount)%>%
  group_by(Customer)%>%
  summarise(count=sum(Amount))%>%
  filter(count!=0)%>%
  arrange(count)
kable(tail(m5))
```


### Change in amount with number of tickets
```{r fig.width=10, message=FALSE, warning=FALSE, paged.print=FALSE}
x<-merge(m2,m5,by="Customer")
kable(head(x))

ggplot(x,aes(x$count.x,x$count.y,color=x$count.y))+
  theme_minimal()+
  geom_point()+
  geom_smooth(method="lm",se=F,color="red")+
  labs(x="Tickets by Customer",y="Total Amount",title="Change in amount with number of tickets")
```